### ISSUE TITLE
New release of parity backend broke `secp256kfun`

### ISSUE THREAD

**Issue by h4sh3d** [LLFourn/secp256kfun#75]
Release `0.1.6` of `secp256kfun_parity_backend` broke `secp256kfun` version `0.6.2`, it took me some time to figure out why this lib compiled a week ago and not anymore today without a new release, so I open this here if others run into that issue. Fell free to label that _wontfix_.

Potential fix for people using `secp256kfun` version `0.6.2`, just pin the old version in Cargo.toml:
```toml
secp256kfun = "0.6"
secp256kfun_parity_backend = "=0.1.5"
```
